#!/usr/bin/env bash
#script prints out numbers one to five on new lines while sending the output to a file named with todays date
echo "one" > $(date +%m-%d-%Y)-file.txt
echo "two" >> $(date +%m-%d-%Y)-file.txt
echo "three" >> $(date +%m-%d-%Y)-file.txt
echo "four" >> $(date +%m-%d-%Y)-file.txt
echo "five" >> $(date +%m-%d-%Y)-file.txt

